apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-all-in-one-deployment
  labels:
    app: jaeger-all-in-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-all-in-one
  template:
    metadata:
      labels:
        app: jaeger-all-in-one
    spec:
      containers:
        - image: jaegertracing/all-in-one:latest
          name: jaeger
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
              protocol: TCP
            - containerPort: 16686
              protocol: TCP
            - containerPort: 14268
              protocol: TCP
            - containerPort: 14250
              protocol: TCP
#            - containerPort: 9411
#              protocol: TCP
          readinessProbe:
            httpGet:
              path: "/"
              port: 14269
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-all-in-one-service
spec:
  selector:
    app: jaeger-all-in-one
  ports:
    - name: "16686"
      protocol: TCP
      port: 16686
      targetPort: 16686
      nodePort: 32006
    - name: "6831" 
      protocol: UDP
      port: 6831
      targetPort: 6831
      nodePort: 32007
  type: NodePort
