version: '3.7'

services:
  minimal-api-clean-architecture-db:
    image: mcr.microsoft.com/mssql/server:2019-latest

  portainer:
    image: portainer/portainer-ce

  elasticsearch:
    image: ahmettugur/elasticsearch
    build:
      context: ../elasticsearch/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}

  kibana:
    image: ahmettugur/kibana
    build:
      context: ../kibana/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}

  rabbitmq:
    image: "rabbitmq:3.11.11-management"

  jaeger:
    image: jaegertracing/all-in-one
  
  zipkin-server:
    image: openzipkin/zipkin

  consul:
    image: consul

networks:
  blogNetwork:
    driver: bridge

volumes:
  portainer_data:
  elasticsearch:
  jaeger-data:
