apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elasticsearch-deployment
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch-deployment-container
          env:
            - name: discovery.type
              value: single-node
            - name: node.name
              value: elasticsearch
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: cluster.name
              value: docker-cluster
            - name: network.host
              value: "0.0.0.0"
            - name: xpack.license.self_generated.type
              value: trial
            - name: xpack.security.enabled
              value: "false"
          #image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
          image: ahmettugur/elasticsearch
          readinessProbe:
            exec:
              command:
              - curl
              - localhost:9200/_cluster/health
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
              - curl
              - localhost:9200/_cluster/health
            initialDelaySeconds: 30
            periodSeconds: 10
          ports:
            - containerPort: 9200
            - containerPort: 9300
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      name: "9200"
      port: 9200
      targetPort: 9200
      nodePort: 32001
    - protocol: TCP
      name: "9300"
      port: 9300
      targetPort: 9300
      nodePort: 32002
  type: NodePort