apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kibana-node
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  strategy: {}
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - env:
            - name: server.name
              value: kibana
            - name: server.host
              value: "0.0.0.0"
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch-service:9200
            - name: monitoring.ui.container.elasticsearch.enabled
              value: "true"
          #image: docker.elastic.co/kibana/kibana:8.7.0
          image: ahmettugur/kibana
          readinessProbe:
            exec:
              command:
              - curl
              - localhost:5601/api/status
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
              - curl
              - localhost:5601/api/status
            initialDelaySeconds: 30
            periodSeconds: 10
          name: kibana
          ports:
            - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
spec:
  selector:
    app: kibana
  ports:
    - protocol: TCP
      name: "5601"
      port: 5601
      targetPort: 5601
      nodePort: 32003
  type: NodePort