apiVersion: apps/v1
kind: Deployment
metadata:
  name: clean-architecture-grpc-deployment
  labels:
    app: clean-architecture-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clean-architecture-grpc
  template:
    metadata:
      labels:
        app: clean-architecture-grpc
    spec:
      containers:
        - name: clean-architecture-grpc-service
          image: ahmettugur/clean-architecture-grpc-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__Default
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: db-connection-string-secret
            - name: RabbitMqConfig__VHostname
              valueFrom:
                configMapKeyRef:
                  name: clean-architecture-configmap
                  key: rabbitmq_config_vhostname
            - name: RabbitMqConfig__Hostname
              valueFrom:
                configMapKeyRef:
                  name: clean-architecture-configmap
                  key: rabbitmq_config_hostname
            - name: RabbitMqConfig__Username
              valueFrom:
                configMapKeyRef:
                  name: clean-architecture-configmap
                  key: rabbitmq_config_username
            - name: RabbitMqConfig__Password
              valueFrom:
                configMapKeyRef:
                  name: clean-architecture-configmap
                  key: rabbitmq_config_password
            - name: RabbitMqConfig__Port
              valueFrom:
                configMapKeyRef:
                  name: clean-architecture-configmap
                  key: rabbitmq_config_port
            - name: RabbitMqConfig__Exchange
              valueFrom:
                configMapKeyRef:
                  name: clean-architecture-configmap
                  key: rabbitmq_config_exchange
            - name: RabbitMqConfig__ExchangeType
              valueFrom:
                configMapKeyRef:
                  name: clean-architecture-configmap
                  key: rabbitmq_config_exchange_type
            - name: AppSettings__ApplicationName
              value: MinimalApiCleanArchitecture.GrpcService
            - name: AppSettings__Instance
              value: "2"
            - name: JaegerSettings__Host
              valueFrom:
                configMapKeyRef:
                  name: clean-architecture-configmap
                  key: jaeger_host
            - name: JaegerSettings__Port
              valueFrom:
                configMapKeyRef:
                  name: clean-architecture-configmap
                  key: jaeger_port
            - name: JaegerSettings__SourceName
              value: "Grpc"
            - name: JaegerSettings__ServiceName
              value: "MinimalApiCleanArchitecture.GrpcService"
            - name: ExporterSettings__UseExporter
              value: "jaeger"
            - name: Zipkin__Endpoint
              value: "http://zipkin-server-service:9411/api/v2/spans"
            - name: ConsulConfig__Address
              valueFrom:
                configMapKeyRef:
                  name: clean-architecture-configmap
                  key: consul_address
            - name: ConsulConfig__ServiceAddress
              value: "http://clean-architecture-grpc-service:8002"
            - name: ConsulConfig__ServiceName
              value: "MinimalApiCleanArchitectureGrpcService"
            - name: ConsulConfig__ServiceId
              value: "MinimalApiCleanArchitectureGrpcService"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: clean-architecture-grpc-service
spec:
  selector:
    app: clean-architecture-grpc
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8080
      nodePort: 31001
  type: NodePort
