apiVersion: v1
kind: ConfigMap
metadata:
  name: mssql-connection-configmap
  labels:
    app: clean-architecture
data:
  db-connection-string: Server=mssql-service;Database=MinimalApiCleanArchitecture;User=sa;Password=Ahmet1990;TrustServerCertificate=true;