apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-deployment
  labels:
    app: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - image: hashicorp/consul
          name: consul
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8500
            - containerPort: 8600
              protocol: TCP
            - containerPort: 8600
              protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: consul-service
spec:
  selector:
    app: consul
  ports:
    - name: "8500"
      protocol: TCP
      port: 8500
      targetPort: 8500
      nodePort: 32010
    - name: "8600"
      protocol: TCP
      port: 8600
      targetPort: 8600
      nodePort: 32011
    - name: "86002"
      protocol: UDP
      port: 8600
      targetPort: 8600
      nodePort: 32012
  type: NodePort
