services:
  clean-architecture-db:
    image: mcr.microsoft.com/mssql/server:2019-latest

  portainer:
    image: portainer/portainer-ce

#  clean-architecture-minimal-api:
#    image: ahmettugur/clean-architecture-minimal-api
#    build:
#      context: ../
#      dockerfile: src/Presentation/MinimalApiCleanArchitecture.MinimalApi/Dockerfile
#
#  clean-architecture-grpc-service:
#    image: ahmettugur/clean-architecture-grpc-service
#    build:
#      context: ../
#      dockerfile: src/Presentation/MinimalApiCleanArchitecture.GrpcService/Dockerfile
#
#  clean-architecture-log-consumer:
#    image: ahmettugur/clean-architecture-log-consumer
#    build:
#      context: ../
#      dockerfile: src/Consumers/MinimalApiCleanArchitecture.LogConsumer/Dockerfile

  elasticsearch:
    image: ahmettugur/elasticsearch
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}

  kibana:
    image: ahmettugur/kibana
    build:
      context: kibana/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}

  rabbitmq:
    image: "rabbitmq:3.11.11-management"

  jaeger:
    image: jaegertracing/all-in-one:latest
  
  zipkin-server:
    image: openzipkin/zipkin

  consul:
    image: hashicorp/consul

networks:
  blogNetwork:
    driver: bridge

volumes:
  portainer_data:
  elasticsearch:
  jaeger-data:
